name: Lint Test

on:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]

jobs:
  lint-test:
    permissions:
      contents: read
      pull-requests: write
    uses: advmeds/advmeds-actions/.github/workflows/fe-lint-test.yml@v1
    secrets: inherit
